# Generated by Django 6.0.3 on 2026-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_kinetic_energy', models.FloatField(help_text='Minimum KE in ft-lbs')),
                ('min_momentum', models.FloatField(help_text='Minimum momentum in slug-ft/s')),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
