# Generated by Django 6.0.3 on 2026-04-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BowSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mathews V3X 33', max_length=100)),
                ('ibo_speed', models.IntegerField(help_text='IBO rated speed in FPS')),
                ('draw_weight', models.IntegerField(help_text='Actual draw weight in lbs')),
                ('draw_length', models.FloatField(help_text='Draw length in inches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArrowBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Elk Setup Heavy', max_length=100)),
                ('arrow_length', models.FloatField(help_text='Cut length in inches')),
                ('num_vanes', models.IntegerField(default=3)),
                ('total_arrow_weight', models.FloatField(blank=True, null=True)),
                ('arrow_speed', models.FloatField(blank=True, null=True)),
                ('kinetic_energy', models.FloatField(blank=True, null=True)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('foc', models.FloatField(blank=True, help_text='Front of Center %', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadhead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.broadhead')),
                ('insert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.insert')),
                ('nock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.nock')),
                ('shaft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.arrowshaft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.vane')),
                ('bow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.bowsetup')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
