# Generated by Django 6.0.3 on 2026-04-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('insert_type', models.CharField(choices=[('insert', 'Insert'), ('outsert', 'Outsert'), ('halfout', 'Half-Out')], max_length=10)),
                ('weight_grains', models.FloatField(help_text='Weight in grains')),
                ('compatible_diameter', models.CharField(blank=True, help_text='e.g. .204, .246', max_length=20)),
                ('material', models.CharField(blank=True, help_text='e.g. Aluminum, Brass, Stainless Steel', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer')),
            ],
            options={
                'ordering': ['manufacturer', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Nock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('nock_type', models.CharField(choices=[('press', 'Press-Fit'), ('pin', 'Pin')], max_length=10)),
                ('weight_grains', models.FloatField(help_text='Weight in grains')),
                ('compatible_diameter', models.CharField(blank=True, help_text='e.g. .204, .246', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['manufacturer', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Broadhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('broadhead_type', models.CharField(choices=[('fixed', 'Fixed Blade'), ('mechanical', 'Mechanical'), ('hybrid', 'Hybrid')], max_length=12)),
                ('weight_grains', models.FloatField(help_text='Weight in grains')),
                ('cutting_diameter', models.FloatField(blank=True, help_text='Cutting diameter in inches', null=True)),
                ('num_blades', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer')),
            ],
            options={
                'ordering': ['manufacturer', 'model_name'],
                'unique_together': {('manufacturer', 'model_name', 'weight_grains')},
            },
        ),
        migrations.CreateModel(
            name='ArrowShaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('spine', models.IntegerField(help_text='Spine rating (e.g. 300, 340, 400)')),
                ('gpi', models.FloatField(help_text='Grains per inch')),
                ('inner_diameter', models.FloatField(help_text='Inner diameter in inches')),
                ('outer_diameter', models.FloatField(blank=True, help_text='Outer diameter in inches', null=True)),
                ('straightness', models.CharField(blank=True, help_text='e.g. .001, .003, .006', max_length=20)),
                ('stock_length', models.FloatField(default=32.0, help_text='Stock length in inches')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer')),
            ],
            options={
                'ordering': ['manufacturer', 'model_name', 'spine'],
                'unique_together': {('manufacturer', 'model_name', 'spine')},
            },
        ),
        migrations.CreateModel(
            name='Vane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=150)),
                ('length_inches', models.FloatField(help_text='Vane length in inches')),
                ('height_inches', models.FloatField(blank=True, help_text='Vane height in inches', null=True)),
                ('weight_grains', models.FloatField(help_text='Weight per vane in grains')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['manufacturer', 'model_name'],
                'unique_together': {('manufacturer', 'model_name')},
            },
        ),
    ]
